In [1]:
import numpy as np
import os
import sklearn 
import pandas as pd

In [6]:
df = pd.read_csv('data/train.csv')

df

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,697,705,Asus,Chromebook Flip,2 in 1 Convertible,12.5,Full HD / Touchscreen 1920x1080,Intel Core M M3-6Y30 0.9GHz,4GB,64GB Flash Storage,Intel HD Graphics 515,Chrome OS,1.2kg,669.00
1,435,442,Asus,Rog Strix,Gaming,17.3,Full HD 1920x1080,AMD Ryzen 1600 3.2GHz,8GB,256GB SSD + 1TB HDD,AMD Radeon RX 580,Windows 10,3.2kg,1695.00
2,735,743,Lenovo,V310-15IKB (i7-7500U/4GB/1TB/FHD/W10),Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,4GB,1TB HDD,Intel HD Graphics 620,Windows 10,1.85kg,779.00
3,864,875,Dell,XPS 13,Ultrabook,13.3,Quad HD+ / Touchscreen 3200x1800,Intel Core i7 7660U 2.5GHz,16GB,512GB SSD,Intel Iris Plus Graphics 640,Windows 10,1.29kg,2240.00
4,1176,1194,Lenovo,B51-80 (i7-6500U/4GB/1008GB/FHD/W7),Notebook,15.6,Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,1.0TB Hybrid,Intel HD Graphics 520,Windows 7,2.32kg,825.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
907,920,934,Dell,Vostro 3568,Notebook,15.6,1366x768,Intel Core i5 7200U 2.5GHz,4GB,1TB HDD,AMD Radeon R5 M420,Windows 10,2.18kg,684.99
908,298,303,Lenovo,IdeaPad 310-15ABR,Notebook,15.6,Full HD 1920x1080,AMD A10-Series 9600P 2.4GHz,6GB,1TB HDD,AMD Radeon R5 430,Windows 10,2.4kg,499.00
909,919,933,MSI,GL62M 7RD,Gaming,15.6,Full HD 1920x1080,Intel Core i5 7300HQ 2.5GHz,8GB,128GB SSD + 1TB HDD,Nvidia GeForce GTX 1050,Windows 10,2.2kg,1119.91
910,717,725,Lenovo,110-15ACL (A6-7310/4GB/500GB/W10),Notebook,15.6,1366x768,AMD A6-Series 7310 2GHz,4GB,500GB HDD,AMD Radeon R4,Windows 10,2.19kg,298.00
911,987,1001,Lenovo,Legion Y520-15IKBN,Gaming,15.6,IPS Panel Full HD 1920x1080,Intel Core i7 7700HQ 2.8GHz,8GB,128GB SSD + 1TB HDD,Nvidia GeForce GTX 1060,Windows 10,2.5kg,1189.00

In [7]:
df.head()

,id,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,697,705,Asus,Chromebook Flip,2 in 1 Convertible,12.5,Full HD / Touchscreen 1920x1080,Intel Core M M3-6Y30 0.9GHz,4GB,64GB Flash Storage,Intel HD Graphics 515,Chrome OS,1.2kg,669.0
1,435,442,Asus,Rog Strix,Gaming,17.3,Full HD 1920x1080,AMD Ryzen 1600 3.2GHz,8GB,256GB SSD + 1TB HDD,AMD Radeon RX 580,Windows 10,3.2kg,1695.0
2,735,743,Lenovo,V310-15IKB (i7-7500U/4GB/1TB/FHD/W10),Notebook,15.6,Full HD 1920x1080,Intel Core i7 7500U 2.7GHz,4GB,1TB HDD,Intel HD Graphics 620,Windows 10,1.85kg,779.0
3,864,875,Dell,XPS 13,Ultrabook,13.3,Quad HD+ / Touchscreen 3200x1800,Intel Core i7 7660U 2.5GHz,16GB,512GB SSD,Intel Iris Plus Graphics 640,Windows 10,1.29kg,2240.0
4,1176,1194,Lenovo,B51-80 (i7-6500U/4GB/1008GB/FHD/W7),Notebook,15.6,Full HD 1920x1080,Intel Core i7 6500U 2.5GHz,4GB,1.0TB Hybrid,Intel HD Graphics 520,Windows 7,2.32kg,825.0

In [8]:
df.describe()

                id    laptop_ID      Inches  Price_euros
count   912.000000   912.000000  912.000000    912.00000
mean    652.099781   661.273026   15.060746   1126.92034
std     375.428905   380.297415    1.412363    696.08887
min       0.000000     1.000000   10.100000    174.00000
25%     332.500000   338.500000   14.000000    589.00000
50%     655.500000   663.500000   15.600000    952.00000
75%     980.500000   994.500000   15.600000   1499.00000
max    1301.000000  1319.000000   18.400000   4899.00000

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 912 entries, 0 to 911
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                912 non-null    int64
 1   laptop_ID         912 non-null    int64
 2   Company           912 non-null    str
 3   Product           912 non-null    str
 4   TypeName          912 non-null    str
 5   Inches            912 non-null    float64
 6   ScreenResolution  912 non-null    str
 7   Cpu               912 non-null    str
 8   Ram               912 non-null    str
 9   Memory            912 non-null    str
 10  Gpu               912 non-null    str
 11  OpSys             912 non-null    str
 12  Weight            912 non-null    str
 13  Price_euros       912 non-null    float64
dtypes: float64(2), int64(2), str(10)
memory usage: 210.5 KB

In [10]:
df["Company"].unique()

<ArrowStringArray>
[     'Asus',    'Lenovo',      'Dell',  'Mediacom',   'Toshiba',        'HP',
      'Acer',     'Apple',       'MSI',   'Fujitsu',   'Samsung',     'Chuwi',
 'Microsoft',     'Razer',    'Xiaomi',    'Huawei',    'Google',      'Vero',
        'LG']
Length: 19, dtype: str

In [11]:
df["Company"]

0        Asus
1        Asus
2      Lenovo
3        Dell
4      Lenovo
        ...
907      Dell
908    Lenovo
909       MSI
910    Lenovo
911    Lenovo
Name: Company, Length: 912, dtype: str

In [12]:
df["laptop_ID"]

0       705
1       442
2       743
3       875
4      1194
       ...
907     934
908     303
909     933
910     725
911    1001
Name: laptop_ID, Length: 912, dtype: int64

In [ ]:
df["laptop_ID"].value_counts()
# son todas distintas

laptop_ID
705     1
442     1
743     1
875     1
1194    1
       ..
934     1
303     1
933     1
725     1
1001    1
Name: count, Length: 912, dtype: int64