# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [24]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [25]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [26]:
chipo.describe().T

           count        mean         std  min     25%    50%     75%     max
order_id  4622.0  927.254868  528.890796  1.0  477.25  926.0  1393.0  1834.0
quantity  4622.0    1.075725    0.410186  1.0    1.00    1.0     1.0    15.0

In [27]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

### Step 3. Name of the max valued product

In [28]:
chipo["item_price"] = chipo["item_price"].str.replace("$", "", regex=False).astype(float)

prod_caro = chipo.loc[(chipo['item_price']/chipo['quantity']).idxmax(), 'item_name']
print(prod_caro)

# CREO COLUMNA calculo precio unitario porque item_price uestra el precio total,no por unidad
chipo["unit_price"] = chipo["item_price"] / chipo["quantity"]

Steak Salad Bowl

### Step 4. How many products cost more than $10.00?

In [29]:
prods_mas_10_dol = chipo[chipo["unit_price"] > 10]
len(prods_mas_10_dol)

1034

In [ ]:
chipo[chipo["unit_price"] > 10]["item_name"].nunique() # unique saca la lista

25

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [32]:
# tengoq eu contar pedidos únicos
'''en la tarea Occupation usé el método nunique() que encontré para que me devuelva el número de elementos
distintos en un eje especificado y me sirve ahora para este:'''
ped_prod_mas_10 = chipo[chipo["unit_price"] > 10]["order_id"].nunique()
ped_prod_mas_10

787

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [ ]:
''' pedidos cuyo total > 10, no productos individuales
no es lo mismo, un pedido puede tener productos baratitos, pero sumar más de 10
groupby() agrupa datos para obtener total gastado por pedido y sum() suma los precios
de todos los productos dentro de ese pedido '''
total_por_pedido = chipo.groupby("order_id")["item_price"].sum()
peds_total_mayor_10 = (total_por_pedido > 10).sum() # cuento cuántos pedidos tienen un total superior a 10
peds_total_mayor_10

np.int64(1834)

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [ ]:

peds_prod_uno_10 = chipo[(chipo["item_price"] > 10)]["order_id"].nunique()
peds_prod_uno_10

# ["order_id"].nunique()
# devuelva order_id y dentro de esa columna quedarte con las q no se repiten

863

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [37]:


tabla_precios = chipo[["item_name", "unit_price"]].drop_duplicates()
tabla_precios

                                  item_name  unit_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl        8.49
...                                     ...         ...
3989                          Chicken Salad        8.19
4235                           Chicken Bowl        8.50
4237                    Chips and Guacamole        4.25
4509                                  Chips        1.99
4510                          Barbacoa Bowl       11.49

[139 rows x 2 columns]

### Step 6. Sort by the name of the item

In [38]:
tabla_precios.sort_values("item_name")

              item_name  unit_price
298   6 Pack Soft Drink        6.49
4510      Barbacoa Bowl       11.49
471       Barbacoa Bowl       11.48
115       Barbacoa Bowl        8.99
39        Barbacoa Bowl       11.75
...                 ...         ...
186   Veggie Salad Bowl       11.25
960   Veggie Salad Bowl        8.75
1395  Veggie Soft Tacos        8.49
738   Veggie Soft Tacos       11.25
781   Veggie Soft Tacos        8.75

[139 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [39]:
'''fila_max = chipo.loc[chipo["unit_price"].idxmax(), 'quantity'].sum()
print(fila_max)'''

chipo[["item_name", "quantity"]][chipo["item_price"] == chipo["item_price"].max()]
# de chipo quiero las cols item y quantity, quiero como condicion sobre las dos clolumnas es que item price sea el max
# (genero una mascara que solo es True donde el item_price es el max de esa columna)
# filtro lo fijo en el item prise, pero lo quiero ver

                         item_name  quantity
3598  Chips and Fresh Tomato Salsa        15

In [ ]:
chipo.loc[chipo["item_price"].idxmax()]
# con idmax() solo captura la primera que sale
# la máscara captura todos los que coinciden con True

order_id                                      1443
quantity                                        15
item_name             Chips and Fresh Tomato Salsa
choice_description                             NaN
item_price                                   44.25
unit_price                                    2.95
Name: 3598, dtype: object

In [ ]:
# creo que puedo ordenar y luego pedir el primero
chipo.sort_values("item_price", ascending=False).iloc[0]["quantity"]

np.int64(15)

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [ ]:
chipo[chipo["item_name"] == "Veggie Salad Bowl"].shape[0]
# en cuantas filas sale veggie salad bowl

18

### Step 9. How many times did someone order more than one Canned Soda?

In [48]:
# chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)].shape[0]
# así no, porque si lsale en más de una fila, se repiten pedidos

chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)]["order_id"].nunique()

18