# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [3]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Name of the max valued product

In [5]:
prod_caro = chipo.loc[(chipo['item_price']/chipo['quantity']).idxmax(), 'item_name']
print(prod_caro)

TypeError: unsupported operand type(s) for /: 'str' and 'int'

### Step 4. How many products cost more than $10.00?

In [ ]:
prods_mas_10_dol = chipo[chipo["item_price"] > 10]
len(prods_mas_10_dol)

0

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [ ]:
# tengoq eu contar pedidos únicos, no líneas como hice antes
'''en la tarea Occupation usé el método nunique() que encontré para que me devuelva el número de elementos
distintos en un eje especificado y me sirve ahora para este:'''
ped_prod_mas_10 = chipo[chipo["item_price"] > 10]["order_id"].nunique()
ped_prod_mas_10

863

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [ ]:
''' pedidos cuyo total > 10, no productos individuales
no es lo mismo, un pedido puede tener productos baratitos, pero sumar más de 10
groupby() agrupa datos para obtener total gastado por pedido y sum() suma los precios
de todos los productos dentro de ese pedido '''
total_por_pedido = chipo.groupby("order_id")["item_price"].sum()
peds_total_mayor_10 = (total_por_pedido > 10).sum() # cuento cuántos pedidos tienen un total superior a 10
peds_total_mayor_10

np.int64(1834)

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [ ]:
'''busco filas donde item_price > 10 Y, ADEMÁS, para asegurarme de que es un precio
unitario, igualo quantity == 1. uso nunique para contar num de elementos distintos''' 
peds_prod_uno_10 = chipo[(chipo["item_price"] > 10) & (chipo["quantity"] == 1)]["order_id"].nunique()
peds_prod_uno_10

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [ ]:
# calculo precio unitario porque item_price uestra el precio total,no por unidad
chipo["unit_price"] = chipo["item_price"] / chipo["quantity"]

chipo[["item_name", "unit_price"]] # muestro el nombre del prod y su precio unitario

                                  item_name  unit_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl        8.49
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [12]:
chipo.sort_values("item_name")

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [ ]:
fila_max = chipo.loc[chipo["unit_price"].idxmax(), 'quantity'].sum()
print(fila_max)

2

In [ ]:
# creo qeu puedo ordenar y leugo pedir el primero
chipo.sort_values("unit_price", ascending=False).iloc[0]["quantity"]
# no me sale lo mismo que en el código de arriba, así que debe de haber algo mal, pero no lo localizo

np.int64(1)

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [8]:
chipo[chipo["item_name"] == "Veggie Salad Bowl"].shape[0]

18

### Step 9. How many times did someone order more than one Canned Soda?

In [11]:
chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)].shape[0]

20